export const LightTheme = {
  white: "#fff",
  black: "#000",
  gray: "gray",
  lightblue: "#e3eeff",
  lightgray: "lightgray",
  blue: "#1d4ed8",
  medium: "#b0b0b0",
  text: "black",
  red: "red",
  darkred: "#991b1b",
  lightred: "#fef2f2",
  green: "green",
  lightgreen: "#f2fef2",
  darkgreen: "#1b991b",
}
export const DarkTheme = {
  white: "#121212",
  black: "#ffffff",
  gray: "#b0b0b0",
  lightblue: "#1e293b",
  lightgray: "#2e2e2e",
  blue: "#60a5fa",
  medium: "#b0b0b0",
  text: "lightgray",
  red: "red",
  lightred: "#4b1c1c",
  darkred: "#991b1b",
  green: "green",
  lightgreen: "#f2fef2",
  darkgreen: "#1b991b",
}
